library(poweRlaw)
SONYorig = read.csv('~/Downloads/SONY.csv', na.strings = c('null'))
SONY = subset(SONYorig, complete.cases(SONYorig))
SONYLogdiff = diff(log(SONY$Close))
s_mean = mean(SONYLogdiff)
s_sd = sd(SONYLogdiff)
SONYLogdiff_z = (SONYLogdiff - s_mean) / s_sd
SONYpos = conpl$new(SONYLogdiff_z[SONYLogdiff_z > 0])
#SONYneg = conpl$new(-SONYLogdiff_z[SONYLogdiff_z < 0])
est_pos = estimate_xmin(SONYpos)
#est_neg = estimate_xmin(SONYneg)
SONYpos$setXmin(est_pos)
#SONYneg$setXmin(est_neg)
plot(SONYpos)
lines(SONYpos, lwd=2)
#plot(SONYneg)
#lines(SONYneg, lwd=2)
